### PR TITLE
Cross compile for scala 2.12 and 2.13 versions

### PR DESCRIPTION
**Pull request by guyonvarch**
Removing tut which caused trouble and we don’t use it.

### CODE REVIEW

**Review by etaque — CHANGES_REQUESTED** [review]
I'm fine with disabling tut, but shouldn't we also remove tut-related markup in Readme as well as tut sbt plugin?

**Comment by guyonvarch** [comment]
> I'm fine with disabling tut, but shouldn't we also remove tut-related markup in Readme as well as tut sbt plugin?

Yes, done with https://github.com/dividat/docless/pull/3/commits/e7ef69951a5d7b932f2407769cf612c30a916a42.

**Review by etaque — APPROVED** [review]
:+1:

**Comment by guyonvarch** [comment]
Feel free to merge if that’s good for you, I don’t have the rights myself.

**Pull request merged**
